name: C CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --recursive --init
    - run: make test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --recursive --init
    - run: make build
